build_from:  # https://github.com/hassio-addons/addon-debian-base
  aarch64: ghcr.io/hassio-addons/debian-base:7.3.4
  amd64: ghcr.io/hassio-addons/debian-base:7.3.4
  armhf: ghcr.io/hassio-addons/debian-base:7.3.4
  armv7: ghcr.io/hassio-addons/debian-base:7.3.4
