build_from:  # https://github.com/hassio-addons/addon-debian-base
  # aarch64: ghcr.io/hassio-addons/debian-base:8.1.4
  amd64: ghcr.io/hassio-addons/debian-base:8.1.4
  # armhf: ghcr.io/hassio-addons/debian-base:8.1.4
  # armv7: ghcr.io/hassio-addons/debian-base:8.1.4
  # i386: ghcr.io/hassio-addons/debian-base:8.1.4
