build_from:  # https://github.com/hassio-addons/addon-debian-base
  # aarch64: ghcr.io/hassio-addons/debian-base:7.8.2
  amd64: ghcr.io/hassio-addons/debian-base:7.8.2
  # armhf: ghcr.io/hassio-addons/debian-base:7.8.2
  # armv7: ghcr.io/hassio-addons/debian-base:7.8.2
  # i386: ghcr.io/hassio-addons/debian-base:7.8.2
