build_from:  # https://github.com/hassio-addons/addon-debian-base
  # aarch64: ghcr.io/hassio-addons/debian-base:7.5.1
  amd64: ghcr.io/hassio-addons/debian-base:7.5.1
  # armhf: ghcr.io/hassio-addons/debian-base:7.5.1
  # armv7: ghcr.io/hassio-addons/debian-base:7.5.1
  # i386: ghcr.io/hassio-addons/debian-base:7.5.1
