name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  workflows:
    permissions:
      pull-requests: read
    uses: finleyfamily/workflows/.github/workflows/hass-addon.ci.yml@master
