name: Deploy

on:
  release:
    types:
      - published
  workflow_run:
    workflows:
      - CI
    branches:
      - master
    types:
      - completed

jobs:
  auth:
    name: Create app token
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.app-token.outputs.token }}
    steps:
      - name: 🏗 Create app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.FINLEY_APP_ID }}
          private-key: ${{ secrets.FINLEY_APP_PRIVATE_KEY }}
  workflows:
    needs: auth
    uses: finleyfamily/workflows/.github/workflows/hass-addon.deploy.yml@master
    secrets:
      DISPATCH_TOKEN: ${{ needs.auth.outputs.token }}
