name: release-drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  release-drafter:
    name: release-drafter
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Release Drafter
        uses: release-drafter/release-drafter@v6.0.0
        env:
          # using a PAT here will allow releases to trigger a build/release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
